env:
  browser: true
  es2021: true
  node: true
  jquery: true
  commonjs: true
  amd: true
extends: eslint:recommended
globals:
  ELCONF: true
  ELMP: true
  underscore: "readonly"
  _: "readonly"
  requirejs: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: "warn"
  no-prototype-builtins: "warn"
  no-empty:
    - "warn"
    - allowEmptyCatch: true